$ANSIBLE_VAULT;1.1;AES256
36306132373931623764353835623963666666313236316435393461616262613232386536653138
3262303131353761326134363965653137636266306437370a653332623564363963613838373665
63313134623537653861303137303864616262366330613533636632663561653064373030313264
3733646164303463610a333739376638383734623930363566313231303637383930363164633231
33333930373962626536323764636266383362323231356532343839613430396233393838373361
32313337303139386564393532373233663639316232373335623962636464613961353933623132
61623136626231396164336362643963346134366163666138623263373432336462376437376138
32633338643163383864353633366632363066383336323532613933323133313634653137383462
34613133373332363364336338363732356535373838386566636365366335316539306661336263
65623666393732383031643139306333373732306565343336613730333233663362303136646634
62393261633465353235363263666137376531613537356430393865386139663664386265356632
61326262633131333461613833346331366664626530323137303633393161663333313534633134
35303538666431356466313265616138393461346637313336313765633136663266656466313566
32616234646338363466386230623964316564643634613265383534313233636366636230613631
35343635373766653030333538636465636530363838666131336265376463633965373039613832
61346636656239363333663237323664656338343664383361393636366439626135636435386262
35316664306239306538356235636536653433356636386532643039323232343734643631353930
35366231386265373833323931653562656462633337363963646564346365366161363564616133
61393132333965343735366462653265303761353035643530366639643432336364393837646330
35323362646563363966626336346337636364313131663433663630353564323631396265663431
65376235363839333364333864366662383037623330623130396335633539333135306233346463
66363763366535383863633465383139326137393536313833323761616661316263613536623836
63616366656631646437343062633962636636623637376639333337633233346363656135336531
65386362373135383163373133663639333962373364393735353935623137326561643766333535
35613237633565666330653232396232336133396466333364656162666366336239
