$ANSIBLE_VAULT;1.1;AES256
31636636363435663962396564643265366638303165346136383034336265663136396436363334
6439353638306530616461333234656537336165353232390a633439386538666437313033353233
66336632316133353063663064363233353632666261333961353238633764333337613337373364
3234343761663934650a393830396161346133623835356561353630356362316638353432396333
65303462366532326339323062326634653038343034353030373538313030316562346264396637
32306130383032363761306236616631643963313836343263336131373464356235656266663566
62643666646532333630373934656535623733373033663536393533336563396166653335313531
33663036346631646365363166656332623161366266356639353934613734636663656561376430
66353563656339393637656536623432653462393262323030323834663837356165333539666361
36363032646364303461666536336131353261306661616632316337396366353961623365326432
32623465363430643634613330356136353037323535616630396633313731373436643432666661
32386262653664303638636231613665336235313661323562626631663831313565396534666634
34643162626433353364643936623930613632346465616561383739323063383164323563316133
32376262646537626336623538343439633664353261303938393265663935323630356336613136
34363537363631653362336230633530646464616663346434356234323062636530396538363131
62353165366536376437343435383835373362666362323863383131663434303732336232333731
62353438333430623933613735616234616133353536373739656332626262346136346363663562
34633865393336303765346538373662306138363365323461313735393562616434333732303839
63363135333238373232653566336530336361623738356239666336323135343933383963383837
39343166643363383132333732616666363538353036306136653834636361306231356264613361
36613836343832353235646337326461636431356565396335323866656532333361353431333633
3431613466613131643734316238393530373539366366343032
